#!/usr/bin/env python
#you can find the library in https://github.com/judplaza/MFRC522-python.git, it is a folk from the original where I add/edited functions to adap them to my project

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522

reader = SimpleMFRC522()

try:
        id = reader.read_id() #this function returns the id in decimal format
        uid = reader.from_dec_to_hex8(id) #this function transforms the previus decimal number into a hex one.
        print("UID hex8: " , uid)
finally:
        GPIO.cleanup()
